jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      id: generate_changelog_file
      name: Changelog Generator from github issues
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        compareLink: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      id: commit
      name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        commit_message: Automatic changelog update
        file_pattern: CHANGELOG.md
    - continue-on-error: true
      id: extract-release-notes
      name: Extract release notes
      uses: ffurrer2/extract-release-notes@v1
      with:
        prerelease: true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create release
      uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.extract-release-notes.outputs.release_notes }}
        draft: false
        name: ${{ github.ref }}
        prerelease: false
        tag: ${{ github.ref }}
name: Changelog
on:
  repository_dispatch:
    types: trigger-ga___changelog.yml
